lizard_box/urls.py
# (c) Nelen & Schuurmans.  GPL licensed, see LICENSE.rst.
from django.conf.urls.defaults import include
from django.conf.urls.defaults import patterns
from django.conf.urls.defaults import url
from django.contrib import admin
from lizard_ui.urls import debugmode_urlpatterns

from lizard_box import views

admin.autodiscover()

urlpatterns = patterns(
    '',
    # url(r'^ui/', include('lizard_ui.urls')),
    # url(r'^map/', include('lizard_map.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^layout/(?P<slug>[^/]+)/',
        views.LayoutView.as_view(),
        name="lizard_box_layoutview"),
    url(r'^box/(?P<name>[^/]+)/',
        views.BoxView.as_view(),
        name="lizard_box_boxview"),
   # url(r'^something_else/$',
    #     views.SomeClassBasedView.as_view(),
    #     name='name_it_too'),
    )
urlpatterns += debugmode_urlpatterns()

lizard_box/models.py
# (c) Nelen & Schuurmans.  GPL licensed, see LICENSE.rst.
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Layout(models.Model):
    """
    A layout consists of one of more columns with contents (boxes).
    """
    title = models.CharField(
        _('title'),
        max_length=80)
    slug = models.SlugField(
        _('slug'),
        help_text=_("Used in the URL."))
    portal_tabs = models.ManyToManyField("PortalTab", through="LayoutPortalTab")

    def __unicode__(self):
        return self.title


class PortalTab(models.Model):
    """
    A portal tab to link to other pages.

    You can define them on each layout.
    """
    TAB_TYPE_LAYOUT = 1
    TAB_TYPE_LINK = 2

    TAB_TYPE_CHOICES = (
        (TAB_TYPE_LAYOUT, "another lizard-box Layout"),
        (TAB_TYPE_LINK, "generic link"))

    name = models.CharField(max_length=40)
    description = models.TextField(null=True, blank=True)
    icon_class = models.CharField(
        max_length=80,
        null=True,
        blank=True,
        help_text="bootstrap iconnames used as action in upper right corner: http://twitter.github.com/bootstrap/base-css.html")

    tab_type = models.IntegerField(
        choices=TAB_TYPE_CHOICES,
        default=TAB_TYPE_LAYOUT)
    destination_slug = models.SlugField(
        help_text="in case of 'another lizard-box Layout'",
        null=True, blank=True)
    destination_url = models.CharField(
        help_text="URL in case of generic link",
        max_length=200,
        null=True, blank=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        """
        Calc destination url. The url does not really represent this
        object. On the other side, it does.
        """
        if self.tab_type == self.TAB_TYPE_LAYOUT:
            return reverse(
                "lizard_box_layoutview",
                kwargs={"slug": self.destination_slug})
        else:
            return self.destination_url


class LayoutPortalTab(models.Model):
    """A portal tab in a layout"""
    layout = models.ForeignKey(Layout)
    portal_tab = models.ForeignKey(PortalTab)
    index = models.IntegerField(default=100)

    class Meta:
        ordering = ('index', )


class Column(models.Model):
    """
    A part of Layout, containing Boxes.
    """
    layout = models.ForeignKey(Layout)
    width = models.IntegerField(
        null=True,
        blank=True,
        help_text=_("Width 1-12 following Twitter Bootstrap scaffolding"))
    index = models.IntegerField(
        default=100,
        help_text=_("Determines order of columns"))
    boxes = models.ManyToManyField("Box", through="ColumnBox")

    class Meta:
        ordering = ('layout', 'index', )

    def __unicode__(self):
        return 'Column {index} (layout {layout})'.format(layout=self.layout,
                                                         index=self.index)


class Box(models.Model):
    """
    A content holding item.

    Can be used to display a part of a screen, or part of an "action" popup in upper right corner of a columnbox.
    """
    BOX_TYPE_TEMPLATE = 1
    BOX_TYPE_IFRAME = 2
    BOX_TYPE_JSLOAD = 3

    BOX_TYPE_CHOICES = (
        (BOX_TYPE_TEMPLATE, "template in box"),
        (BOX_TYPE_IFRAME, "iframe"),
        (BOX_TYPE_JSLOAD, "js load"),
        )

    name = models.CharField(
        _('title'),
        max_length=80)
    slug = models.SlugField(
        _('slug'),
        help_text=_("Used in the URL."))
    icon_class = models.CharField(
        max_length=80,
        null=True,
        blank=True,
        help_text="bootstrap iconnames used as action in upper right corner: http://twitter.github.com/bootstrap/base-css.html")
    box_type = models.IntegerField(choices=BOX_TYPE_CHOICES, default=BOX_TYPE_TEMPLATE)
    template = models.TextField(
        null=True, blank=True,
        help_text="For box_type 'template in box', or as optional selector in js loader")
    url = models.TextField(
        null=True,
        blank=True,
        help_text=_("For box_type 'iframe', url for iframe or source url for js loader")
        )

    class Meta:
        ordering = ('slug', )

    def __unicode__(self):
        return self.name

    def render(self, url=None):
        if url is None:
            url = self.url
        if self.box_type == self.BOX_TYPE_TEMPLATE:
            if self.template:
                return self.template
            else:
                return 'Empty box: fill template of box named "%s"' % self.name
        elif self.box_type == self.BOX_TYPE_IFRAME:
            return '<iframe src="%s" frameborder="0" class="box">IFrame contents</iframe>' % url
        elif self.box_type == self.BOX_TYPE_JSLOAD:
            # data_src = self.url
            # if self.template:
            #     data_src += ' ' + self.template
            return '<div class="javascript-replace" data-src="%s">Loading</div>' % (
                url)

    def render_popup(self):
        """The popup rendering adds the option "popup=true" to the src url"""
        url = self.url + '?popup=true'
        return self.render(url=url)

    @property
    def icon_class_or_default(self):
        if self.icon_class:
            return self.icon_class
        else:
            return 'icon-plus-sign'


class ColumnBox(models.Model):
    """
    A box in a column.
    """
    name = models.CharField(max_length=80, null=True, blank=True)
    box = models.ForeignKey(Box)
    column = models.ForeignKey(Column)
    index = models.IntegerField(
        default=100,
        help_text=_("Determines order of columns"))
    height = models.IntegerField(
        null=True,
        blank=True,
        help_text=_("Height in pixels, stretch if omitted"))
    # Upper right corner, actions can be info, maximize
    action_boxes = models.ManyToManyField(
        "Box", related_name="action_boxes", null=True, blank=True)
    maximize_action = models.BooleanField(default=False)
    refresh_millis = models.IntegerField(
        default=0,
        help_text="refresh this columnbox every xxx millis, 0 for no refreshment")

    html_color_header = models.CharField(
        max_length=20, null=True, blank=True,
        help_text="optionally provide html header color")
    html_color_body = models.CharField(
        max_length=20, null=True, blank=True,
        help_text="optionally provide html body color")

    class Meta:
        ordering = ('index', )

    def __unicode__(self):
        return '{name} (in column {column})'.format(name=self.name,
                                                    column=self.column)

    # add box_parameters?
    def render_box(self):
        return self.box.render()

    def display_name(self):
        """Display this name in a view"""
        if self.name:
            return self.name
        else:
            return self.box.name

    def actions(self):
        """
        Standard actions show in a popup. However, special actions can
        be "grabbed" by name in javascript lizard_box.js. These
        special actions do not exist yet.
        """
        result = list(self.action_boxes.all())
        if self.maximize_action:
            action_box = self.box
            action_box.icon_class = 'icon-plus-sign'
            result.insert(0, action_box)
        return result

lizard_box/templates/lizard_box/box.html
{% extends "lizard_ui/realbase.html" %}

{% block title %}
  {{ view.box.name }}
{% endblock title %}

TODO:
This css is now customized for one specific box.

{% block css %}
  {{ block.super }}
  <style type="text/css">
    #main-selector {
        list-style-type: none;
     }
    #main-selector li {
        border: 0;
    }
    .text-center {
        text-align: center;
    }
    .text-light {
        color: #bbbbbb;
    }
    .row {
        padding: 10px 0px 20px 0px;
    }
  </style>
{% endblock css %}

{% block main-area %}
  <div class="container">
    {% autoescape off %}
      {{ view.box.render }}
    {% endautoescape %}
  </div>
  <div id="footer">
  <div style="padding-top: 2px; padding-left: 310px;">
    <a href="http://www.fugro.nl"><img src="{{ STATIC_URL }}lizard_box/logo_fugro.png" style="height: 90%"></a>&nbsp;&nbsp;
    <a href="http://www.nelen-schuurmans.nl/"><img src="{{ STATIC_URL }}lizard_box/logo_nelenschuurmans.png" style="height: 90%"></a>
  </div>
  </div>
{% endblock main-area %}

lizard_box/templates/lizard_box/layout.html
{% extends "lizard_ui/realbase.html" %}

{% block title %}
{{ view.layout }}
{% endblock title %}


Testing css
{% block css %}
{{ block.super }}
<style type="text/css">
.box-header {
    background-image: -webkit-linear-gradient(left, #157681, #157681);
    background-image: -o-linear-gradient(left, #157681, #157681);
    background-image: linear-gradient(left, #157681, #157681);
    background-repeat: repeat-x;
    //border-bottom: 1px solid #0C68B0;
    padding: 5px 13px 5px 13px;
    -webkit-border-top-right-radius: 8px;
    -webkit-border-top-left-radius: 8px;
    -moz-border-radius-topright: 8px;
    -moz-border-radius-topleft: 8px;
    border-top-left-radius: 8px;
    border-top-right-radius: 8px;

    color: white;
    background-color: #157681;
    margin: 4px 6px 0px 6px;
    padding-top: 4px;
    padding-bottom: 4px;
    padding-left: 10px;
    padding-right: 6px;

    font-weight: bold;
    letter-spacing: 1px;
    font-size: 13px;
    font-family: sans-serif;
}
.box {
    -webkit-border-top-right-radius: 10px;
    -webkit-border-top-left-radius: 10px;
    -webkit-border-bottom-right-radius: 10px;
    -webkit-border-bottom-left-radius: 10px;
    border-top-left-radius: 10px;
    border-top-right-radius: 10px;
    border-bottom-left-radius: 10px;
    border-bottom-right-radius: 10px;
    -moz-border-radius-topright: 10px;
    -moz-border-radius-bottomright: 10px;
    -moz-border-radius-bottomleft: 10px;
    -moz-border-radius-topleft: 10px;
    padding-top: 2px;
    -webkit-overflow-scrolling:touch;
}
.box-dialog {
    display: none;
    width: 0;
    height: 0;
}
.box-contents {
//    padding: 0px 6px 4px 10px;
    margin: 0px 6px 2px 6px;
    overflow: auto;
    height: 100%;
}
#main-container {
    margin-top: 10px;
}
.action-icon {
    float: right;
}
iframe.box {
    margin-top: 5px;
    width: 99%;
    height: 97%;
}
.nav-rounded {
    -webkit-border-top-right-radius: 0px;
    -webkit-border-top-left-radius: 0px;
    -webkit-border-bottom-right-radius: 8px;
    -webkit-border-bottom-left-radius: 8px;
    border-top-left-radius: 0px;
    border-top-right-radius: 0px;
    border-bottom-left-radius: 8px;
    border-bottom-right-radius: 8px;
    -moz-border-radius-topright: 0px;
    -moz-border-radius-topleft: 0px;
    -moz-border-radius-bottomleft: 8px;
    -moz-border-radius-bottomright: 8px;
}
form input[type=checkbox] {
    margin-right: 5px;
}
{# levee portal #}
.box-action.image-map-dialog {
    overflow: auto;
    -webkit-overflow-scrolling:touch;
}
</style>
{% endblock css %}


{% block javascript %}
  {{ block.super }}
  <script type="text/javascript"
          src="{{ STATIC_URL }}lizard_box/lizard_box.js"></script>
{% endblock javascript %}

You can use vertical-item-fixed like this:
      <div class="box vertical-item-fixed" data-height="100">
      </div>


{% block main-area %}
<div class="container-fluid" id="main-container">
  <div class="row-fluid">
    {% for column in view.layout.column_set.all %}
      <div class="span{{ column.width }} evenly-spaced-vertical">
        {% for columnbox in column.columnbox_set.all %}
          <div class="box {% if columnbox.height %}vertical-item-fixed{% else %}vertical-item{% endif %}"
               data-refresh-millis="{{ columnbox.refresh_millis }}"
               data-slug="{{ columnbox.box.slug }}"
               data-temp-id="{{ column.index }}{{ columnbox.index }}"
               {% if columnbox.height %}
                 data-height="{{ columnbox.height }}"
               {% endif %}
               {% if columnbox.html_color_body %}
                 style="background-color: {{ columnbox.html_color_body }};"
               {% endif %}>
            <div class="box-header"
                 {% if columnbox.html_color_header %}
                   style="background-color: {{ columnbox.html_color_header}}; background-image: -webkit-linear-gradient(left, {{ columnbox.html_color_header }}, {{ columnbox.html_color_header }}); border-bottom: 1px solid {{ columnbox.html_color_header }};"
                 {% endif %}>
              {{ columnbox.display_name }}

              {% if user.is_superuser %}
                <a href="/admin/lizard_box/columnbox/{{ columnbox.pk }}/"
                   title="Edit layout box"
                   class="icon-edit action-icon icon-white">&nbsp;</a>
                <a href="/admin/lizard_box/box/{{ columnbox.box.pk }}/"
                   title="Edit box contents"
                   class="icon-edit action-icon">&nbsp;</a>
              {% endif %}

              {% for action in columnbox.actions %}
              <a href="#"
                 class="box-action {{ action.icon_class_or_default }} action-icon icon-white"
                 data-temp-id="{{ column.index }}{{ columnbox.index }}{{ action.slug }}"
                 ><div class="box-dialog"
                       data-title="{{ action }}"
                       data-temp-id="{{ column.index }}{{ columnbox.index }}{{ action.slug }}">
                  {% if user.is_superuser %}
                  <a href='/admin/lizard_box/box/{{ action.pk }}/' class='icon-edit action-icon'>&nbsp;</a>
                  {% endif %}
                  {% autoescape off %}{{ action.render_popup }}{% endautoescape %}
              </div></a>
              {% endfor %}
            </div>
            <div class="box-contents">
              {% autoescape off %}
                {{ columnbox.render_box }}
              {% endautoescape %}
            </div>
          </div>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
</div>
<div id="footer">
</div>
{% endblock main-area %}